### ISSUE TITLE
[Bug] Star icon is permanent on Fabric 1.20.1

### ISSUE THREAD

**Issue by rumrunner0** [AHilyard/Highlighter#19]
### Description
Star icon shows up for an item that has been picked up in a hotbar slot. Since _clear_on_hover = false_, it still exists after selecting the hotbar slot. The icon still shows up even when I move the picked up item to another slot and then place completely different item to that "buggy" hotbar slot. The feature works correctly with all other slots (which are not related to the hotbar).

### Note
It worth noting that it works correctly on version 1.1.9 for Fabric (1.20.2, 1.20.4) with _clear_on_select_ option set to _true_.

### Proposal
Please make a fix for Minecraft 1.20.1 or just make an update that will include this new _clear_on_select_ option. Thanks!

### Related
Environment: Minecraft 1.20.1
Mod loader: Fabric 0.15.6
Mod version: 1.1.6

Configuration file content:
_highlighter-common.toml_
```toml
#Client Configuration
[client]

	[client.options]
		# If new item markers should be cleared when the inventory is closed.
		clear_on_close = false
		# If new item markers should be cleared when the item tooltip is displayed.
		clear_on_hover = false
		# If icons should match the color of items names (as shown in tooltips).  Otherwise icons will all be gold.
		item_name_color = false
		# If new item markers should show on the hotbar.
		show_on_hotbar = true

```
